"""Seed data for Exygen Labs: categories + realistic MXN catalog.
Prices in MXN. All products are research-use-only (RUO).
This catalog is fully editable/replaceable from the admin panel.
"""

VIAL_A = 'https://images.pexels.com/photos/9259964/pexels-photo-9259964.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
VIAL_B = 'https://images.pexels.com/photos/5922066/pexels-photo-5922066.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'
VIAL_C = 'https://images.pexels.com/photos/36339062/pexels-photo-36339062.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940'

CATEGORIES = [
    {'name': 'Recuperacion y Tejidos', 'slug': 'recuperacion-tejidos', 'icon': 'HeartPulse',
     'description': 'Peptidos estudiados en reparacion de tejidos, tendones y mucosa gastrica.'},
    {'name': 'Hormona de Crecimiento', 'slug': 'hormona-crecimiento', 'icon': 'Activity',
     'description': 'Secretagogos y peptidos relacionados con la senalizacion de GH.'},
    {'name': 'Metabolicos', 'slug': 'metabolicos', 'icon': 'Flame',
     'description': 'Peptidos de investigacion en metabolismo y composicion corporal.'},
    {'name': 'Longevidad', 'slug': 'longevidad', 'icon': 'Hourglass',
     'description': 'Peptidos estudiados en envejecimiento celular y funcion mitocondrial.'},
    {'name': 'Nootropicos', 'slug': 'nootropicos', 'icon': 'Brain',
     'description': 'Peptidos de investigacion en funcion cognitiva y estres.'},
    {'name': 'Bienestar', 'slug': 'bienestar', 'icon': 'Sparkles',
     'description': 'Peptidos de investigacion en sueno, piel y bienestar general.'},
    {'name': 'Stacks / Combos', 'slug': 'stacks', 'icon': 'Layers',
     'description': 'Combinaciones de peptidos para protocolos de investigacion.'},
    {'name': 'Accesorios', 'slug': 'accesorios', 'icon': 'FlaskConical',
     'description': 'Insumos para investigacion: agua bacteriostatica, viales y jeringas.'},
]


def _p(name, slug, category, sd, desc, presentation, purity, price, stock, img,
       batch, tiers=None, featured=False, is_new=False, form='Liofilizado',
       storage='Conservar a -20 C, protegido de la luz. Reconstituido: 2-8 C.'):
    return {
        'name': name, 'slug': slug, 'category': category, 'short_description': sd,
        'description': desc, 'presentation': presentation, 'form': form, 'purity': purity,
        'price': price, 'tiers': tiers or [], 'stock': stock, 'image_url': img,
        'coa_url': f'https://exygenlabs.com/coa/{slug}.pdf', 'batch_number': batch,
        'storage': storage, 'featured': featured, 'is_new': is_new,
    }


DISCLAIMER = ' Solo para uso en investigacion (RUO). No apto para consumo humano ni animal.'

PRODUCTS = [
    _p('BPC-157 5 mg', 'bpc-157-5mg', 'recuperacion-tejidos',
       'Peptido estudiado en reparacion de tejidos y mucosa gastrica.',
       'BPC-157 es un peptido de investigacion ampliamente estudiado por su rol en la reparacion de tejidos, tendones y la integridad gastrointestinal.' + DISCLAIMER,
       '5 mg / vial', '99.4%', 549, 48, VIAL_A, 'NP-BPC5-2401',
       tiers=[{'min_qty': 3, 'price': 499}, {'min_qty': 6, 'price': 449}], featured=True),
    _p('BPC-157 10 mg', 'bpc-157-10mg', 'recuperacion-tejidos',
       'Mayor concentracion para protocolos de investigacion extendidos.',
       'Presentacion de 10 mg de BPC-157 para estudios que requieren mayor cantidad de material. Pureza verificada por HPLC.' + DISCLAIMER,
       '10 mg / vial', '99.4%', 849, 35, VIAL_A, 'NP-BPC10-2401',
       tiers=[{'min_qty': 3, 'price': 779}, {'min_qty': 6, 'price': 699}], featured=True),
    _p('TB-500 5 mg', 'tb-500-5mg', 'recuperacion-tejidos',
       'Fraccion de timosina beta-4 estudiada en movilidad celular.',
       'TB-500 (fragmento de Timosina Beta-4) es investigado por su papel en la migracion celular y recuperacion tisular amplia.' + DISCLAIMER,
       '5 mg / vial', '99.1%', 749, 30, VIAL_B, 'NP-TB5-2401',
       tiers=[{'min_qty': 3, 'price': 679}], featured=True),
    _p('TB-500 10 mg', 'tb-500-10mg', 'recuperacion-tejidos',
       'Presentacion concentrada de TB-500 para investigacion.',
       'TB-500 en presentacion de 10 mg, liofilizado de alta pureza para estudios de recuperacion tisular.' + DISCLAIMER,
       '10 mg / vial', '99.1%', 1190, 22, VIAL_B, 'NP-TB10-2401'),
    _p('GHK-Cu 50 mg', 'ghk-cu-50mg', 'recuperacion-tejidos',
       'Peptido de cobre estudiado en piel y regeneracion.',
       'GHK-Cu es un peptido de cobre investigado por su rol en la remodelacion de la matriz extracelular y la salud de la piel.' + DISCLAIMER,
       '50 mg / vial', '99.0%', 449, 25, VIAL_C, 'NP-GHK-2401', is_new=True),
    _p('Ipamorelin 5 mg', 'ipamorelin-5mg', 'hormona-crecimiento',
       'Secretagogo selectivo de GH, ampliamente estudiado.',
       'Ipamorelin es un peptido de investigacion estudiado por su senalizacion selectiva de hormona de crecimiento con bajo impacto en cortisol.' + DISCLAIMER,
       '5 mg / vial', '99.3%', 649, 40, VIAL_A, 'NP-IPA5-2401',
       tiers=[{'min_qty': 3, 'price': 589}], featured=True),
    _p('Ipamorelin 10 mg', 'ipamorelin-10mg', 'hormona-crecimiento',
       'Presentacion concentrada de Ipamorelin.',
       'Ipamorelin 10 mg liofilizado para protocolos de investigacion de mayor escala.' + DISCLAIMER,
       '10 mg / vial', '99.3%', 1090, 28, VIAL_A, 'NP-IPA10-2401'),
    _p('CJC-1295 sin DAC 5 mg', 'cjc-1295-no-dac-5mg', 'hormona-crecimiento',
       'Analogo de GHRH de vida media corta.',
       'CJC-1295 sin DAC (Mod GRF 1-29) es estudiado por la liberacion pulsatil de GH en modelos de investigacion.' + DISCLAIMER,
       '5 mg / vial', '99.2%', 749, 26, VIAL_B, 'NP-CJCN5-2401'),
    _p('CJC-1295 DAC 5 mg', 'cjc-1295-dac-5mg', 'hormona-crecimiento',
       'Analogo de GHRH con DAC, vida media prolongada.',
       'CJC-1295 con DAC es investigado por su vida media extendida y senalizacion sostenida de GH.' + DISCLAIMER,
       '5 mg / vial', '99.2%', 949, 20, VIAL_B, 'NP-CJCD5-2401'),
    _p('Sermorelin 5 mg', 'sermorelin-5mg', 'hormona-crecimiento',
       'Analogo de GHRH estudiado en senalizacion de GH.',
       'Sermorelin es un peptido de investigacion analogo de GHRH estudiado por la estimulacion de la hormona de crecimiento.' + DISCLAIMER,
       '5 mg / vial', '99.0%', 749, 18, VIAL_C, 'NP-SER5-2401'),
    _p('Tesamorelin 5 mg', 'tesamorelin-5mg', 'hormona-crecimiento',
       'Analogo de GHRH estudiado en metabolismo de lipidos.',
       'Tesamorelin es investigado por su rol en la senalizacion de GH y el metabolismo del tejido adiposo visceral.' + DISCLAIMER,
       '5 mg / vial', '99.1%', 1190, 14, VIAL_C, 'NP-TES5-2401'),
    _p('MOTS-c 10 mg', 'mots-c-10mg', 'longevidad',
       'Peptido mitocondrial estudiado en metabolismo.',
       'MOTS-c es un peptido derivado mitocondrial investigado por su rol en la homeostasis metabolica y la longevidad.' + DISCLAIMER,
       '10 mg / vial', '99.0%', 890, 16, VIAL_A, 'NP-MOTS-2401', is_new=True),
    _p('Epitalon 10 mg', 'epitalon-10mg', 'longevidad',
       'Tetrapeptido estudiado en telomeros y ritmo circadiano.',
       'Epitalon (Epithalon) es investigado por su rol en la actividad de la telomerasa y la regulacion del ritmo circadiano.' + DISCLAIMER,
       '10 mg / vial', '99.2%', 749, 24, VIAL_B, 'NP-EPI-2401'),
    _p('Selank 10 mg', 'selank-10mg', 'nootropicos',
       'Peptido estudiado en ansiedad y cognicion.',
       'Selank es un peptido de investigacion estudiado por sus efectos ansioliticos y nootropicos en modelos preclinicos.' + DISCLAIMER,
       '10 mg / vial', '99.0%', 649, 30, VIAL_C, 'NP-SEL-2401'),
    _p('Semax 10 mg', 'semax-10mg', 'nootropicos',
       'Peptido estudiado en neuroproteccion y memoria.',
       'Semax es investigado por su rol en la neuroproteccion, BDNF y funcion cognitiva en estudios preclinicos.' + DISCLAIMER,
       '10 mg / vial', '99.0%', 649, 27, VIAL_C, 'NP-SMX-2401'),
    _p('PT-141 10 mg', 'pt-141-10mg', 'bienestar',
       'Bremelanotida, estudiada en funcion sexual.',
       'PT-141 (Bremelanotida) es un peptido de investigacion estudiado por su accion sobre receptores de melanocortina.' + DISCLAIMER,
       '10 mg / vial', '99.0%', 749, 21, VIAL_A, 'NP-PT141-2401'),
    _p('DSIP 5 mg', 'dsip-5mg', 'bienestar',
       'Peptido inductor del sueno profundo (investigacion).',
       'DSIP (Delta Sleep-Inducing Peptide) es investigado por su rol en la regulacion del sueno y el estres.' + DISCLAIMER,
       '5 mg / vial', '98.8%', 649, 19, VIAL_B, 'NP-DSIP-2401'),
    _p('Semaglutida 5 mg', 'semaglutida-5mg', 'metabolicos',
       'Agonista GLP-1 para investigacion metabolica.',
       'Semaglutida es un peptido agonista del receptor GLP-1 investigado en modelos de metabolismo de la glucosa y el apetito.' + DISCLAIMER,
       '5 mg / vial', '99.1%', 849, 15, VIAL_A, 'NP-SEMA-2401', featured=True, is_new=True),
    _p('Tirzepatida 10 mg', 'tirzepatida-10mg', 'metabolicos',
       'Doble agonista GIP/GLP-1 para investigacion.',
       'Tirzepatida es un peptido doble agonista GIP/GLP-1 investigado en modelos de control glucemico y composicion corporal.' + DISCLAIMER,
       '10 mg / vial', '99.0%', 1190, 12, VIAL_A, 'NP-TIRZ-2401', featured=True, is_new=True),
    _p('Stack Recuperacion: BPC-157 + TB-500', 'stack-recuperacion', 'stacks',
       'Combo de investigacion para recuperacion de tejidos.',
       'Combinacion de BPC-157 (5 mg) y TB-500 (5 mg) en un solo kit para protocolos de investigacion enfocados en reparacion de tejidos.' + DISCLAIMER,
       'BPC-157 5 mg + TB-500 5 mg', '99.2%', 1190, 18, VIAL_B, 'NP-STKR-2401',
       tiers=[{'min_qty': 3, 'price': 1090}], featured=True),
    _p('Stack GH: Ipamorelin + CJC-1295', 'stack-gh', 'stacks',
       'Combo de investigacion de senalizacion de GH.',
       'Combinacion de Ipamorelin (5 mg) y CJC-1295 sin DAC (5 mg) para estudios de senalizacion de hormona de crecimiento.' + DISCLAIMER,
       'Ipamorelin 5 mg + CJC-1295 5 mg', '99.2%', 1290, 16, VIAL_B, 'NP-STKG-2401', featured=True),
    _p('Agua Bacteriostatica 30 ml', 'agua-bacteriostatica-30ml', 'accesorios',
       'Diluyente esteril para reconstitucion en laboratorio.',
       'Agua bacteriostatica (alcohol bencilico 0.9%) de 30 ml para reconstitucion de peptidos liofilizados en entornos de investigacion.' + DISCLAIMER,
       '30 ml', 'USP', 250, 80, VIAL_C, 'NP-AGUA-2401', form='Solucion esteril',
       storage='Conservar a temperatura ambiente, protegido de la luz.'),
]
